"""S2: extend booking data for public lookup, area preference and cancellation."""
from alembic import op
import sqlalchemy as sa

revision = "012_booking_extensions"
down_revision = "011_auth_audit_constraints"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column("dat_ban", sa.Column("ma_dat_ban", sa.String(6), nullable=True))
    op.add_column("dat_ban", sa.Column("email", sa.String(254), nullable=True))
    op.add_column("dat_ban", sa.Column("khu_vuc_id", sa.Integer(), nullable=True))
    op.add_column("dat_ban", sa.Column("ly_do_tu_choi", sa.Text(), nullable=True))
    op.add_column("dat_ban", sa.Column("xac_nhan_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("dat_ban", sa.Column("huy_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("dat_ban", sa.Column("khach_toi_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("dat_ban", sa.Column("khong_toi_at", sa.DateTime(timezone=True), nullable=True))

    # Existing rows need a deterministic six-character code before the column
    # can become NOT NULL. New rows are generated by the booking service.
    op.execute("UPDATE dat_ban SET ma_dat_ban = LPAD(id::text, 6, '0') WHERE ma_dat_ban IS NULL")
    op.alter_column("dat_ban", "ma_dat_ban", nullable=False)

    op.create_foreign_key(
        "fk_dat_ban_khu_vuc",
        "dat_ban",
        "khu_vuc",
        ["khu_vuc_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_unique_constraint("uq_dat_ban_ma_dat_ban", "dat_ban", ["ma_dat_ban"])
    op.create_index("ix_dat_ban_so_dien_thoai_trang_thai", "dat_ban", ["so_dien_thoai", "trang_thai"])
    op.create_index("ix_dat_ban_ngay_gio", "dat_ban", ["ngay_dat", "gio_bat_dau"])

    op.drop_constraint("ck_dat_ban_so_luong", "dat_ban", type_="check")
    op.create_check_constraint(
        "ck_dat_ban_so_luong",
        "dat_ban",
        "so_luong_khach >= 1 AND so_luong_khach <= 20",
    )


def downgrade() -> None:
    op.drop_constraint("ck_dat_ban_so_luong", "dat_ban", type_="check")
    op.create_check_constraint(
        "ck_dat_ban_so_luong",
        "dat_ban",
        "so_luong_khach >= 1 AND so_luong_khach <= 30",
    )
    op.drop_index("ix_dat_ban_ngay_gio", table_name="dat_ban")
    op.drop_index("ix_dat_ban_so_dien_thoai_trang_thai", table_name="dat_ban")
    op.drop_constraint("uq_dat_ban_ma_dat_ban", "dat_ban", type_="unique")
    op.drop_constraint("fk_dat_ban_khu_vuc", "dat_ban", type_="foreignkey")
    for column in (
        "khong_toi_at",
        "khach_toi_at",
        "huy_at",
        "xac_nhan_at",
        "ly_do_tu_choi",
        "khu_vuc_id",
        "email",
        "ma_dat_ban",
    ):
        op.drop_column("dat_ban", column)
