import {useEffect,useMemo,useState} from 'react'
import {CheckCircleFilled,CloseOutlined,CopyOutlined,EyeInvisibleOutlined,EyeOutlined,PlusOutlined,ReloadOutlined,SearchOutlined,StopOutlined,TeamOutlined} from '@ant-design/icons'
import {changeEmployeeStatus,checkEmployeePhone,checkEmployeeUsername,createEmployee,getEmployees} from '../services/api'
const roles={QUAN_LY:'Quản lý',PHUC_VU:'Phục vụ',BEP:'Bếp',THU_NGAN:'Thu ngân'}
const empty={full_name:'',phone:'',username:'',role:'PHUC_VU',status:'HOAT_DONG'}
export default function Employees(){
 const[items,setItems]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[q,setQ]=useState(''),[role,setRole]=useState('ALL'),[status,setStatus]=useState('ALL'),[open,setOpen]=useState(false),[form,setForm]=useState(empty),[checking,setChecking]=useState({}),[availability,setAvailability]=useState({}),[saving,setSaving]=useState(false),[created,setCreated]=useState(null),[showPass,setShowPass]=useState(true)
 async function load(){setLoading(true);setError('');try{setItems(await getEmployees())}catch(e){setError(e?.response?.data?.detail||'Không tải được danh sách nhân viên.')}finally{setLoading(false)}}
 useEffect(()=>{load()},[])
 const filtered=useMemo(()=>items.filter(x=>{const s=q.trim().toLowerCase();return(!s||[x.full_name,x.phone,x.username].some(v=>String(v).toLowerCase().includes(s)))&&(role==='ALL'||x.role===role)&&(status==='ALL'||x.status===status)}),[items,q,role,status])
 function setField(k,v){setForm(f=>({...f,[k]:v}));if(k==='phone'||k==='username')setAvailability(a=>({...a,[k]:undefined}))}
 async function verify(k){const v=form[k].trim();if(!v)return;setChecking(c=>({...c,[k]:true}));try{const r=k==='phone'?await checkEmployeePhone(v):await checkEmployeeUsername(v);setAvailability(a=>({...a,[k]:r.available}))}catch(e){setAvailability(a=>({...a,[k]:false}))}finally{setChecking(c=>({...c,[k]:false}))}}
 async function submit(e){e.preventDefault();setSaving(true);setError('');try{const r=await createEmployee({...form,full_name:form.full_name.trim(),phone:form.phone.trim(),username:form.username.trim()});setCreated(r);setShowPass(true);setOpen(false);setForm(empty);setAvailability({});await load()}catch(e){const d=e?.response?.data?.detail;if(d?.field)setAvailability(a=>({...a,[d.field]:false}));setError(d?.message||d||'Không thể tạo tài khoản.')}finally{setSaving(false)}}
 async function toggle(emp){const next=emp.status==='HOAT_DONG'?'DA_NGHI':'HOAT_DONG';if(next==='DA_NGHI'&&!confirm(`Đặt ${emp.full_name} thành Đã nghỉ? Tài khoản sẽ không đăng nhập được nữa.`))return;try{await changeEmployeeStatus(emp.id,next);await load()}catch(e){alert(e?.response?.data?.detail||'Không cập nhật được trạng thái.') }}
 const copy=t=>navigator.clipboard?.writeText(t)
 return <>
  <section className="employee-heading"><div className="employee-title-icon"><TeamOutlined/></div><div><p className="eyebrow">MODULE</p><h1>Quản lý nhân viên</h1><p>Quản lý tài khoản và vai trò của nhân viên trong nhà hàng.</p></div><button className="employee-primary" onClick={()=>setOpen(true)}><PlusOutlined/> Thêm nhân viên</button></section>
  <section className="employee-panel"><div className="employee-filters"><div className="employee-search"><SearchOutlined/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Tìm kiếm theo họ tên, tên đăng nhập, số điện thoại..."/></div><select value={role} onChange={e=>setRole(e.target.value)}><option value="ALL">Tất cả vai trò</option>{Object.entries(roles).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value)}><option value="ALL">Tất cả trạng thái</option><option value="HOAT_DONG">Đang làm việc</option><option value="DA_NGHI">Đã nghỉ</option></select></div>
   {error&&<div className="employee-error">{String(error)}</div>}
   <div className="employee-table-wrap"><table className="employee-table"><thead><tr><th>#</th><th>Họ tên</th><th>Số điện thoại</th><th>Tên đăng nhập</th><th>Vai trò</th><th>Trạng thái</th><th>Thao tác</th></tr></thead><tbody>{loading?<tr><td colSpan="7" className="table-empty">Đang tải...</td></tr>:filtered.length===0?<tr><td colSpan="7" className="table-empty">Chưa có nhân viên phù hợp.</td></tr>:filtered.map((x,i)=><tr key={x.id}><td>{i+1}</td><td><b>{x.full_name}</b></td><td>{x.phone}</td><td>{x.username}</td><td><span className={`role-badge role-${x.role.toLowerCase()}`}>{roles[x.role]||x.role}</span></td><td><span className={`work-status ${x.status==='HOAT_DONG'?'working':'left'}`}><i/>{x.status==='HOAT_DONG'?'Đang làm việc':'Đã nghỉ'}</span></td><td><button className="icon-action" title={x.status==='HOAT_DONG'?'Đặt đã nghỉ':'Cho làm lại'} onClick={()=>toggle(x)}>{x.status==='HOAT_DONG'?<StopOutlined/>:<ReloadOutlined/>}</button></td></tr>)}</tbody></table></div>
  </section>
  {open&&<div className="employee-overlay" onMouseDown={e=>e.target===e.currentTarget&&setOpen(false)}><form className="employee-modal" onSubmit={submit}><button type="button" className="modal-close" onClick={()=>setOpen(false)}><CloseOutlined/></button><h2>Tạo tài khoản nhân viên</h2><div className="employee-form-grid"><label>Họ và tên <em>*</em><input required minLength="2" value={form.full_name} onChange={e=>setField('full_name',e.target.value)} placeholder="Nguyễn Văn An"/></label><label>Vai trò <em>*</em><select value={form.role} onChange={e=>setField('role',e.target.value)}>{Object.entries(roles).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>Số điện thoại <em>*</em><input required value={form.phone} onChange={e=>setField('phone',e.target.value)} onBlur={()=>verify('phone')} placeholder="0987654321"/><FieldState state={availability.phone} checking={checking.phone} ok="Số điện thoại có thể sử dụng" bad="Số điện thoại đã được sử dụng"/></label><label>Trạng thái <em>*</em><div className="status-radios"><label><input type="radio" checked={form.status==='HOAT_DONG'} onChange={()=>setField('status','HOAT_DONG')}/> Đang làm việc</label><label><input type="radio" checked={form.status==='DA_NGHI'} onChange={()=>setField('status','DA_NGHI')}/> Đã nghỉ</label></div></label><label>Tên đăng nhập <em>*</em><input required minLength="3" value={form.username} onChange={e=>setField('username',e.target.value.toLowerCase())} onBlur={()=>verify('username')} placeholder="nguyenvanan"/><FieldState state={availability.username} checking={checking.username} ok="Tên đăng nhập có thể sử dụng" bad="Tên đăng nhập đã được sử dụng"/></label></div><div className="modal-actions"><button type="button" className="employee-secondary" onClick={()=>setOpen(false)}>Hủy</button><button className="employee-primary" disabled={saving||availability.phone===false||availability.username===false}>{saving?'Đang tạo...':'Tạo tài khoản'}</button></div></form></div>}
  {created&&<div className="employee-overlay"><div className="employee-modal success-modal"><button className="modal-close" onClick={()=>setCreated(null)}><CloseOutlined/></button><CheckCircleFilled className="success-big"/><h2>Tạo tài khoản thành công</h2><p>Tài khoản nhân viên đã được tạo. Vui lòng sao chép mật khẩu và cung cấp trực tiếp cho nhân viên.</p><div className="credential-row"><span>Tên đăng nhập</span><b>{created.username}</b><button onClick={()=>copy(created.username)}><CopyOutlined/></button></div><div className="credential-row"><span>Mật khẩu tạm (8 ký tự)</span><b>{showPass?created.temporary_password:'••••••••'}</b><button onClick={()=>setShowPass(v=>!v)}>{showPass?<EyeInvisibleOutlined/>:<EyeOutlined/>}</button><button onClick={()=>copy(created.temporary_password)}><CopyOutlined/></button></div><div className="password-warning">⚠ Mật khẩu này chỉ được hiển thị một lần.<br/>Hãy sao chép và gửi trực tiếp cho nhân viên.</div><button className="employee-primary confirm-password" onClick={()=>setCreated(null)}>Tôi đã lưu mật khẩu</button></div></div>}
 </>}
function FieldState({state,checking,ok,bad}){if(checking)return <small className="field-state">Đang kiểm tra...</small>;if(state===true)return <small className="field-state valid">✓ {ok}</small>;if(state===false)return <small className="field-state invalid">✕ {bad}</small>;return null}
