import { ArrowRightOutlined, CalendarOutlined, CheckCircleOutlined, ClockCircleOutlined, QrcodeOutlined, SafetyCertificateOutlined, ShoppingCartOutlined, TeamOutlined, BarChartOutlined, BellOutlined } from '@ant-design/icons'
const features=[
{icon:SafetyCertificateOutlined,title:'Tài khoản & phân quyền',text:'Quản lý tài khoản nhân viên, đăng nhập an toàn và phân quyền theo vai trò để mỗi người tập trung đúng phần việc.'},
{icon:QrcodeOutlined,title:'Dữ liệu nhà hàng',text:'Khai báo khu vực, bàn, sức chứa, mã QR, nhóm món, món ăn, giá và trạng thái bán trong ngày.'},
{icon:CalendarOutlined,title:'Đặt bàn thông minh',text:'Tiếp nhận đặt bàn theo khung giờ, hạn chế đặt trùng, hỗ trợ xác nhận và xếp bàn rõ ràng.'},
{icon:ShoppingCartOutlined,title:'Gọi món & bếp',text:'Mở phiên gọi món theo bàn, ghi chú, thêm hoặc huỷ món theo quy tắc và theo dõi tiến độ phục vụ.'},
{icon:CheckCircleOutlined,title:'Thanh toán & chốt ca',text:'Sinh hoá đơn tạm tính, ghi nhận thanh toán, đóng bàn và đưa bàn trở về trạng thái sẵn sàng.'},
{icon:BarChartOutlined,title:'Thông báo & báo cáo',text:'Cập nhật các mốc quan trọng và cung cấp số liệu trong ngày để quản lý nắm bắt hoạt động.'}]
export default function Home({onLogin}){return <div className="public-home"><header className="public-nav"><div className="public-brand"><div className="brand-mark">R</div><div><strong>Resto</strong><span>Management</span></div></div><button className="login-button" onClick={onLogin}>Đăng nhập <ArrowRightOutlined/></button></header><main>
<section className="hero-section"><div className="hero-copy"><p className="eyebrow">RESTAURANT MANAGEMENT SYSTEM</p><h1>Vận hành nhà hàng<br/><em>gọn gàng hơn mỗi ngày.</em></h1><p className="hero-text">Một không gian quản lý tập trung cho đặt bàn, khách hàng, thực đơn, gọi món, thanh toán và báo cáo — để đội ngũ phục vụ dành nhiều thời gian hơn cho trải nghiệm của thực khách.</p><div className="hero-actions"><button className="primary-button" onClick={onLogin}>Bắt đầu quản lý <ArrowRightOutlined/></button><a href="#features" className="text-link">Khám phá hệ thống</a></div><div className="hero-trust"><SafetyCertificateOutlined/> Đăng nhập bằng phiên làm việc bảo mật · Phân quyền theo vai trò</div></div><div className="hero-visual"><div className="hero-image-wrap"><img src="https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1200&q=85" alt="Không gian nhà hàng hiện đại"/></div><div className="floating-card booking-float"><div className="float-icon"><CalendarOutlined/></div><div><strong>Đặt bàn hôm nay</strong><span>Quản lý theo khung giờ</span></div><b>24</b></div><div className="floating-card service-float"><CheckCircleOutlined/><span>Bàn 08 đã sẵn sàng</span></div></div></section>
<section className="story-section"><div className="story-image"><img src="https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&w=1000&q=85" alt="Món ăn được phục vụ tại nhà hàng"/></div><div className="story-copy"><p className="eyebrow">ONE PLACE TO RUN YOUR RESTAURANT</p><h2>Từ bàn đặt đến bàn thanh toán, mọi thứ nằm trong một luồng.</h2><p>Hệ thống được thiết kế quanh những công việc diễn ra mỗi ngày tại nhà hàng: khách đặt bàn, nhân viên xác nhận, bếp nhận món, phục vụ cập nhật trạng thái và quản lý chốt số liệu cuối ca.</p><div className="story-points"><span><ClockCircleOutlined/> Theo dõi trạng thái theo thời gian thực</span><span><TeamOutlined/> Phân quyền theo vai trò</span><span><BellOutlined/> Thông báo đúng thời điểm</span></div></div></section>
<section id="features" className="features-section"><div className="section-heading"><p className="eyebrow">MỘT HỆ THỐNG, NHIỀU NGHIỆP VỤ</p><h2>Được xây dựng để đồng hành cùng từng ca làm việc.</h2><p>Từ dữ liệu gốc đến báo cáo cuối ngày, mỗi chức năng đều hướng tới một thao tác rõ ràng và ít bước thừa.</p></div><div className="feature-grid">{features.map(({icon:Icon,title,text})=><article className="feature-card" key={title}><div className="feature-icon"><Icon/></div><h3>{title}</h3><p>{text}</p></article>)}</div></section>
<section className="flow-section"><div><p className="eyebrow">WORKFLOW</p><h2>Một quy trình liền mạch.</h2></div><div className="flow-list"><span>01 <b>Đặt bàn</b></span><ArrowRightOutlined/><span>02 <b>Xác nhận</b></span><ArrowRightOutlined/><span>03 <b>Gọi món</b></span><ArrowRightOutlined/><span>04 <b>Thanh toán</b></span><ArrowRightOutlined/><span>05 <b>Báo cáo</b></span></div></section></main><footer className="public-footer"><div className="public-brand"><div className="brand-mark">R</div><div><strong>Resto</strong><span>Management</span></div></div><span>Modern Restaurant Admin Dashboard</span><button onClick={onLogin}>Đăng nhập hệ thống <ArrowRightOutlined/></button></footer></div>}
